KnowckknowcK/BE

.github/workflows/deployDev.yml, Dockerfile, src/main/java/com/knu/KnowcKKnowcK/controller/HealthCheckController.java
- mysql RDS 연결
- Dockerfile 생성
- github action 적용
---
데이터베이스 엔드포인트 슬랙 시크릿키에 위치
---
---
=> Env/issue #1

.github/workflows/deployDev.yml
- github workflow 수정
- jar 파일 빌드 스크립트 추가
---
---
---
=> Fix : github action workflow 수정

build.gradle, src/main/java/com/knu/KnowcKKnowcK/config/SwaggerConfig.java
- swagger ui 적용
---
노션에 올려둔 사용방법 참고하시면 됩니다.
/api/** 와 매치되는 url에 대해서만 문서화 함.
---
추후 로그인 기능 구현 후 bearer token 포함하여 테스트하도록 수정 예정
---
=> Docs : swagger ui 적용

build.gradle
=> Env: Update build.gradle

src/main/java/com/knu/KnowcKKnowcK/domain/Message.java, src/main/java/com/knu/KnowcKKnowcK/domain/MessageThread.java
- delete cascade 옵션을 적용하여 table drop 이 안되는 오류를 수정
---
---
---
close #14
=> Fix : delete cascade 옵션 적용

src/main/java/com/knu/KnowcKKnowcK/domain/Article.java, src/main/java/com/knu/KnowcKKnowcK/enums/Category.java, src/main/java/com/knu/KnowcKKnowcK/enums/Position.java, src/main/java/com/knu/KnowcKKnowcK/enums/Status.java
- article 카테고리 enum으로 변경
- POLITICS,ECONOMICS,SOCIAL,IT  네가지 카테고리 enum으로 생성
---
- enums 패키지 생성 후 Category,Status,Position enum 생성
---
---
#21
=> Refactor: 기사 카테고리 타입 변경

src/main/java/com/knu/KnowcKKnowcK/controller/DebateRoomController.java, src/main/java/com/knu/KnowcKKnowcK/controller/MessageController.java, src/main/java/com/knu/KnowcKKnowcK/controller/PubSubController.java, src/main/java/com/knu/KnowcKKnowcK/domain/Message.java, src/main/java/com/knu/KnowcKKnowcK/domain/MessageThread.java, src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/PreferenceDto.java, src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/PreferenceRequestDto.java, src/main/java/com/knu/KnowcKKnowcK/exception/ErrorCode.java, src/main/java/com/knu/KnowcKKnowcK/service/DebateRoomService.java, src/main/java/com/knu/KnowcKKnowcK/service/MessageService.java
프론트엔드에서 메세지를 받으면 구독한 url에 적절하게 보내도록 수정도 했습니다.
---
---
---
=> Feat/issue #18

src/main/java/com/knu/KnowcKKnowcK/controller/DebateRoom/DebateRoomController.java, src/main/java/com/knu/KnowcKKnowcK/controller/DebateRoom/MessageController.java, src/main/java/com/knu/KnowcKKnowcK/controller/DebateRoom/PubSubController.java, src/main/java/com/knu/KnowcKKnowcK/controller/DebateRoomController.java, src/main/java/com/knu/KnowcKKnowcK/controller/MessageController.java, src/main/java/com/knu/KnowcKKnowcK/domain/Message.java, src/main/java/com/knu/KnowcKKnowcK/domain/MessageThread.java, src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/DebateRoomResponseDto.java, src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/MessageResponseDto.java, src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/MessageThreadResponseDto.java, src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/PreferenceResponseDto.java, src/main/java/com/knu/KnowcKKnowcK/repository/PreferenceRepository.java, src/main/java/com/knu/KnowcKKnowcK/service/debateRoom/DebateRoomService.java, src/main/java/com/knu/KnowcKKnowcK/service/debateRoom/MessageService.java
- 댓글 수 카운트 기능
- 메세지 좋아요 수 카운트 기능
- 메세지 스레드 DTO 개선
---
대부분 프론트엔드 DTO 관련 수정이고, 로직 자체에 큰 변화는 없어요.
토론방의 경우 조금 더 지켜보고 속도적인 면이 더 필요하다 싶으면 
REDIS 활용해서 구현하는 쪽으로 바꿀 수도 있을 거 같긴 합니다.
---
---
=> Feat/issue #34

src/main/java/com/knu/KnowcKKnowcK/converter/StringToScoreConverter.java, src/main/java/com/knu/KnowcKKnowcK/domain/SummaryFeedback.java, src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/SummaryResponseDto.java, src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveOpinionServiceImpl.java, src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveSummaryServiceImpl.java, src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/ChatGptContext.java, src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/ChatGptService.java, src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/ChatGptServiceTest.java, src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/OpinionFeedbackService.java, src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/SummaryFeedbackService.java, src/test/java/com/knu/KnowcKKnowcK/controller/articleSummary/SaveSummaryTest.java, src/test/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveOpinionServiceTest.java
- `@DisplayName("AI 피드백이 옳지 않은 점수를 반환하면 예외처리한다.")` 테스트 실행 완료
- enum 에 맞지 않는 점수를 반환 시 CustomException 처리
---
- PR #48 이 도메인 수정 전 코드라 깃액션 통과를 못하고 있는듯함 #51 컨펌 후 pull 받아서 재시도 예정
---
---
=> Fix: `Summary` 도메인 속성 타입 변경에 맞게 수정

src/main/java/com/knu/KnowcKKnowcK/domain/Article.java, src/main/java/com/knu/KnowcKKnowcK/domain/Opinion.java, src/main/java/com/knu/KnowcKKnowcK/domain/OpinionFeedback.java, src/main/java/com/knu/KnowcKKnowcK/domain/Summary.java, src/main/java/com/knu/KnowcKKnowcK/domain/SummaryFeedback.java
- 256바이트 이상의 필드에 대해 데이터 타입 변경
---
기존의 @Lob 을 이용할 시 tinytext 로 생성되는 것을 확인
---
---
closes #56
=> !HOTFIX: 256byte 이상의 필드 데이터 타입 변경

src/main/java/com/knu/KnowcKKnowcK/controller/DebateRoom/DebateRoomController.java, src/main/java/com/knu/KnowcKKnowcK/controller/DebateRoom/PubSubController.java, src/main/java/com/knu/KnowcKKnowcK/domain/MemberDebate.java, src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/DebateRoomMemberDto.java, src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/DebateRoomResponseDto.java, src/main/java/com/knu/KnowcKKnowcK/repository/MemberDebateRepository.java, src/main/java/com/knu/KnowcKKnowcK/service/debateRoom/DebateRoomService.java
- 토론방 참여 시 찬/반 결정 로직 추가
- 토론방 참여자 리스트 반환 API 추가
- 기타 오류 수정
---
토론방 관련 백엔드 기능은 구현이 사실상 완료된 거 같아요.
Redis 관련 리팩토링은 개발 일정 보고 차질이 없을 거 같으면 진행할게요~
---
---
=> Feat/issue #47

src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/LoadArticlesController.java, src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/LoadSummaryController.java, src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/SummaryHistoryResponseDto.java, src/main/java/com/knu/KnowcKKnowcK/enums/Status.java, src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryService.java, src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryServiceImpl.java, src/test/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryServiceTest.java
- 진행 중인 요약(`Status.DONE`) 이 있으면 해당 요약의 `id`, `content`, `takenTime`, `status` 반환
- 지문에 처음 요약을 작성하거나, 이미 완료한 (`Status.DONE`) 요약밖에 없다면 `Status.NEW` 인 상태만 반환
---
- 단위 테스트 완료
---
x
---
=> Feat: 요약 작성 히스토리 로드

src/test/java/com/knu/KnowcKKnowcK/controller/myInfo/MyPageControllerTest.java
- 토론방 조회 test에서 데이터베이스 의존성이 생겨 test 실패 -> 주석으로 test 실행 안하도록 수정
---
---
---
=> Chore: 토론방 조회 test 주석처리

build.gradle, src/main/java/com/knu/KnowcKKnowcK/KnowcKKnowcKApplication.java, src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/LoadSummaryController.java, src/main/java/com/knu/KnowcKKnowcK/dto/prompt/SummaryPrompt.java, src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryServiceImpl.java, src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveSummaryServiceImpl.java, src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/SummaryFeedbackService.java
- `spring-retry` 의존성 추가
- 피드백이 양식대로 나오지 않을 경우 `@Retryable` 로 재시도 (최대 3번 재시도 가능, 대기 시간 2초)
- `/load/`-> `/load`
- memberRepository 메서드 인자 오류 수정
---
---
- 과거 summary 들은 보관해두기로 했었는지...?
- 지금은 integrity error가 있어서 같은 기사에 여러개 저장이 안되는 것 같고 덮어쓰기만 될 것 같음
---
=> Fix/issue #70

src/main/java/com/knu/KnowcKKnowcK/domain/Opinion.java
- FeedbackContent 필드 추가
---
테이블 크기 제한때문에 feedback을 일단 3000으로 임시로 해뒀습니다. 추후에 수정이 필요하면 크기제한에 맞게 조정하면 될 것 같습니다! 
---
---
=> Refactor: FeedbackContent 필드 추가

.github/workflows/deployDev.yml, .github/workflows/testAndBuild.yml, Dockerfile, docker-compose.yml, src/main/java/com/knu/KnowcKKnowcK/controller/ProfileCheckController.java
- mysql 컨테이너를 이용하여 테스트 환경 분리
---
---
---
=> Feat: github action test 환경 분리

.github/workflows/deployDev.yml, src/main/java/com/knu/KnowcKKnowcK/controller/ProfileCheckController.java
=> Feat/issue #60

.github/workflows/deployDev.yml
테스트 단계에서 이미 패스했기 때문에 중복하여 실행하지 않음
- deploy 시간 단축을 위해 test 제외
---
---
---
=> Env: 배포시 테스트 작업 제외

src/main/java/com/knu/KnowcKKnowcK/config/SwaggerConfig.java, src/main/java/com/knu/KnowcKKnowcK/config/WebSecurityConfig.java, src/main/java/com/knu/KnowcKKnowcK/controller/AccountController.java
- swagger 에서 jwt를 이용한 인증을 포함하도록 하기 위함.
---
---
---
closes #5
=> Feat: swagger Jwt 설정, 접근 허용

src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/ArticleListController.java, src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadArticlesService.java, src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadArticlesServiceImpl.java, src/main/java/com/knu/KnowcKKnowcK/service/chatGptService/SummaryFeedbackService.java, src/test/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadArticlesServiceTest.java
로그인 인증 전 임시 userId 변경
x
---
x
---
x
---
=> Fix: 로그인 인증 전 임시 userId 변경

src/main/java/com/knu/KnowcKKnowcK/config/WebSecurityConfig.java
- 인증 필요없는 api 추가
---
사소한 수정이라 리뷰 없이 머지하겠습니다.
---
---
#105
=> Fix: 인증 필요없는 api 추가

src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/OpinionController.java, src/main/java/com/knu/KnowcKKnowcK/controller/debateRoom/DebateRoomController.java, src/main/java/com/knu/KnowcKKnowcK/controller/debateRoom/MessageController.java
- PathVariable 파라미터명 명시
---
---
---
closes #108
=> !HOTFIX: PathVariable 파라미터명 명시

src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/OpinionController.java, src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/SummaryController.java, src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/OpinionRequestDto.java, src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/SummaryRequestDto.java, src/main/java/com/knu/KnowcKKnowcK/service/articleOpinion/SaveOpinionService.java, src/main/java/com/knu/KnowcKKnowcK/service/articleOpinion/SaveOpinionServiceImpl.java, src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryService.java, src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryServiceImpl.java, src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveSummaryService.java, src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveSummaryServiceImpl.java, src/test/java/com/knu/KnowcKKnowcK/controller/articleSummary/SaveSummaryTest.java, src/test/java/com/knu/KnowcKKnowcK/service/articleOpinion/SaveOpinionTest.java, src/test/java/com/knu/KnowcKKnowcK/service/articleSummary/LoadSummaryServiceTest.java
- 문해력 진단 부분에 jwt를 적용함
---
---
---
=> Refactor: 문해력 진단 부분 jwt 적용

src/main/java/com/knu/KnowcKKnowcK/controller/articleSummary/SummaryController.java
=> Fix: userId requestParam을 삭제

src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/SummaryRequestDto.java
=> Fix: SummaryRequestDto writer 재추가

src/main/java/com/knu/KnowcKKnowcK/authenticationHandler/CustomAuthenticationFailureHandler.java, src/main/java/com/knu/KnowcKKnowcK/authenticationHandler/JwtAccessDeniedHandler.java, src/main/java/com/knu/KnowcKKnowcK/authenticationHandler/JwtAuthenticationEntryPoint.java
=> Fix/issue #121 handler Fix

src/main/java/com/knu/KnowcKKnowcK/controller/AccountController.java, src/main/java/com/knu/KnowcKKnowcK/exception/ErrorCode.java
- 이메일 인증 response 수정 
---
---
---
=> Fix/issue #121 이메일 인증 response 수정

src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/DebateRoomResponseDto.java, src/main/java/com/knu/KnowcKKnowcK/service/debateRoom/DebateRoomService.java
- 토론방에서 자기 입장을 바로 알 수 있게 수정
---
---
---
=> Fix: 토론방 입장 시 자기 입장을 보여줌

src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/MySummaryResponseDto.java
=> Fix: DTO 필드 수정

src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MyProfileController.java, src/main/java/com/knu/KnowcKKnowcK/domain/Member.java, src/main/java/com/knu/KnowcKKnowcK/service/myPage/MyPageService.java
- DTO 대신 String으로 받아서 파싱
- null 체크해서 바뀐 값만 update
---
---
---
=> Fix: 회원가입시 media type 에러 해결

src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/DebateRoomResponseDto.java
- 백엔드 서버 시간을 프론트측으로 넘겨줌 -> 클라이언트의 시간대에 상관없어짐
---
---
---
#140
=> Refactor: 토론방 시간 계산 로직 개선

src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/MyDebateRoomResponseDto.java, src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/MyOpinionResponseDto.java, src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/MySummaryResponseDto.java
- 요약,견해 DTO 필드 추가
- 토론방 ID 필드 추가
---
---
---
=> Refactor: DTO 필드 수정

src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/ProfileUpdateRequestDto.java, src/main/java/com/knu/KnowcKKnowcK/service/myPage/MyPageService.java
- 비밀번호 수정시 암호화 처리해서 업데이트
- 프로필 수정 시 나머지 필드 null 체크 로직 추가
---
---
#138 
---
=> Fix: 비밀번호 수정 시 암호화

src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/SummaryResponseDto.java, src/main/java/com/knu/KnowcKKnowcK/enums/Score.java, src/main/java/com/knu/KnowcKKnowcK/service/articleSummary/SaveSummaryServiceImpl.java
-  `Score` enum에서 score String과 점수 int를 매핑함
---
---
---
=> Feat: 문해력 진단 시 경험치 제공

src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/DashboardResponseDto.java, src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/MySummaryResponseDto.java, src/main/java/com/knu/KnowcKKnowcK/service/myPage/MyDebateroomService.java, src/main/java/com/knu/KnowcKKnowcK/service/myPage/MyPageService.java, src/main/java/com/knu/KnowcKKnowcK/service/myPage/MySummaryService.java
=> Feat: 대시보드 DTO 경험치 필드 추가

src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/MySummaryResponseDto.java, src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/OpinionResponseDto.java
- DTO에서 article 전체를 전달하기에 문제 발생-> 필요한 필드 일부만 전달
---
---
---
=> !HOTFIX: 내 요약 조회시 지연로딩으로 인한 문제

src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/MySummaryResponseDto.java
프로트에서 navigate를 위한 id 추가
- 필드 추가
---
---
---
=> Refactor: Summary DTO 수정

src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MyProfileController.java, src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/DashboardResponseDto.java, src/main/java/com/knu/KnowcKKnowcK/enums/Score.java, src/main/java/com/knu/KnowcKKnowcK/repository/SummaryFeedbackRepository.java, src/main/java/com/knu/KnowcKKnowcK/service/myPage/MyPageService.java, src/main/java/com/knu/KnowcKKnowcK/service/myPage/MySummaryService.java, src/test/java/com/knu/KnowcKKnowcK/controller/myInfo/MyProfileControllerTest.java, src/test/java/com/knu/KnowcKKnowcK/service/myPage/MyPageServiceTest.java, src/test/java/com/knu/KnowcKKnowcK/service/myPage/MySummaryServiceTest.java
- 작성 완료한 요약에 대해서만 인정
- 오늘 획득한 경험치 반환 
---
견해에 대해서는 경험치를 주지 않고 작성 완료한 요약에 대해서만 부여
대시보드에서 strike 일 수에 대해서는 작성 완료한 요약에 한하여 인정
---
---
=> Refactor/issue #168

src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MyOpinionController.java, src/main/java/com/knu/KnowcKKnowcK/service/myPage/MyOpinionService.java
- 기사 id로 사용자가 작성한 견해 개별 조회 기능
---
요약페이지에서 견해 페이지로 이동시 사용
---
---
=> Feat: 사용자 견해 개별 조회

src/main/java/com/knu/KnowcKKnowcK/config/SecurityConfig.java, src/main/java/com/knu/KnowcKKnowcK/config/jwtConfig/JwtFilter.java, src/main/java/com/knu/KnowcKKnowcK/config/jwtConfig/JwtSecurityConfig.java, src/main/java/com/knu/KnowcKKnowcK/controller/AccountController.java, src/main/java/com/knu/KnowcKKnowcK/dto/requestdto/NewAuthRequestDto.java, src/main/java/com/knu/KnowcKKnowcK/dto/responsedto/NewAuthResponseDto.java, src/main/java/com/knu/KnowcKKnowcK/service/account/TokenService.java
=> Refactor/issue #172 만료 토큰 갱신 로직 수정

src/main/java/com/knu/KnowcKKnowcK/config/WebSocketConfig.java
=> Fix: 웹소켓 dev url 허용

src/main/java/com/knu/KnowcKKnowcK/service/debateRoom/DebateRoomService.java
- 토론방 나가기 로직 에러 수정
---
---
---
#180
=> Fix: 토론방 나가기 로직 에러 수정

src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MyDebateRoomController.java, src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MyOpinionController.java, src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MyProfileController.java, src/main/java/com/knu/KnowcKKnowcK/controller/myInfo/MySummaryController.java
=> Docs: swagger 태그 컨트롤러에 맞게 수정
